spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 594b9ccc4ca095ded249
            client-secret: 7c995575084832470926e121e7b770394f73321c
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user